version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    reviewers:
      - "Nexus-Mods/nexusmods-app-developers"
    labels:
      - "area-dependencies"
    allow:
      - dependency-name: "System.*"
      - dependency-name: "Microsoft.*"
      - dependency-name: "NexusMods.*"
      - dependency-name: "Avalonia*"
    ignore:
      # NOTE(erri120): "special" dependencies that are tied to the roslyn compiler version
      - dependency-name: "Microsoft.CodeAnalysis.CSharp*"
    groups:
      System:
        patterns:
          - "System.*"
      Microsoft:
        patterns:
          - "Microsoft.*"
      NexusMods:
        patterns:
          - "NexusMods.*"
      Avalonia:
        patterns:
          - "Avalonia*"
