name: Mod Install Tests

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "./src/**"
      - "./tests/**"
      - "**.props"
      - "**.targets"

jobs:
  build:

    name: Test ${{matrix.game}} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    environment: test

    env:
      NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}

    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]
        game: [cyberpunk2077, darkestdungeon, sifu, stardewvalley]

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Stress Test
        run: dotnet run --project ./src/NexusMods.App/NexusMods.App.csproj -- stress-test -g ${{matrix.game}} -o ${{ github.step_summary }}

      - uses: codecov/codecov-action@v3
        with:
          flags: networking_tests, ${{runner.os}}
          verbose: true
