name: Mod Install Tests

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/mod_install_tests.yaml"
      - "./src/**"
      - "./tests/**"
      - "**.props"
      - "**.targets"

jobs:
  build:

    name: Test ${{matrix.game}} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    environment: test

    env:
      NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        game: [stardewvalley]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup .NET Core SDK 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Stress Test
        continue-on-error: true
        run: dotnet run --project ./src/NexusMods.App/NexusMods.App.csproj -- as-main stress-test -g ${{matrix.game}} -o ${{ github.step_summary }}
