name: Networking Tests

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    
    name: Test ${{ matrix.project }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    
    environment: test
    
    env:
      NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
    
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [Windows]

    steps:
      - uses: actions/checkout@v3

      #- name: Setup .NET Core SDK 7.0.x
      #  uses: actions/setup-dotnet@v3
      #  with:
      #    dotnet-version: '7.0.x'

      - name: Set Permissions
        if: runner.os != 'Windows'
        run: chmod -R +x src/ArchiveManagement/NexusMods.FileExtractor/Extractors

      - name: Clean Tests
        run: dotnet clean

      - name: Tests
        run: dotnet test --filter RequiresNetworking=True --collect:"XPlat Code Coverage;Format=opencover"

      - uses: codecov/codecov-action@v3
        with:
          flags: networking_tests, ${{runner.os}}
          verbose: true 
